/*this is where our homies will be made*/

USE homeyhelp_db;

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("candespo", "dcandace@business.org", 5235849310, "Hi my name is Candace Desposito. I work at BusinessCo right here in Oakland as a business person. I like to cook and have social gatherings.", "cooking, cycling, hiking", 46, "female", 2000, 95, 87, 79, "business lady", true, false, "NA", "Oakland", 94613)

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("jakeman", "jjakman@majorsearchengine.com",9152259746, "My name is Jake Jakman and I'm a software developer at a major internet company in San Francisco. I am looking for someone who is clean and has their act together. I like to play video games and hang out at breweries", "gaming, downhill mountain biking, frisbee golf", 35, "male", 2000, 89, 67, 73, "software developer", true, false, "NA", "San Francisco", 94133)

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("howdyPartner", "johnwayne@gmail.com", 2141267697, "Howdy I'm John Wayne. I know I know, but sadly no relation. Im new to the area and am looking for a fun house with a couple of cool guys. I enjoy anything to do with the outdoors and love trying new things.","skeet shooting, call of duty, old movies", 27, "male", 1500,69, 78, 99, "A/C Technician", true, true, "420", "Oakland", 94605)

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("kfreedomeagle","freedomfromgov@privateserver.is", 9257895463, "Ha, nice try CIA. If we are matched i will meet you somewhere the governent can't listen", "finding the truth", 56, "male",1000, 55, 61, 42, "Construction Worker", true, false, "NA", "San Ramon", 94582 )

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("Jgirl","Jgirldancer@gmail.com", 5106793145, "Hi my name is Jaleah Williams, I'm a professional dancer and I just moved into town. I love meeting new people and hope we can be friends as well as roomies.", "going dancing, comedy clubs, fashion", 21, "female", 2000, 75, 92, 86, "Dancer/Choreographer", true, true "420", "Los Angeles", 90028)

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("cindythomson", "candycrush@hotmail.com", 5102489763, "Hi I'm Cindy Thomson. I'm am looking for someone who is kind and and open. You must be neat, responsible and no drugs.", "cooking, dancing, reality tv", 30, "female", 2000, 95, 96, 86, "Small Business Owner", true, false, "NA", "Lafayette", 94549)

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("JeffSpanner", "jeffspanner@jefland.net", 4152623483, "Hey I am a baker at a locally owned bakery. I am looking for a cool roommate who wont mind my crazy hours. I love to practice my craft in my spare time so I hope you like sweets.", "baking, craft beer, mountain biking", 34, "male", 1800, 84, 72, 94, "Baker", true, true, "420", "Belvedere Tiburon", 94920)

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("loudobbs", "loudobbs@capitalfinance.com", 4153258844, "I am Lou Dobbs. I am a finance manager for many important people. My wife kicked me out and took half my stuff so Im just looking for a temporary place while I get myself sorted out. If we get along well I am open to staying. I am clean and can grill a mean steak.", "bbq, football, craft beer, sky diving", 46, "male", 3000, 95, 82, 89, true, false, "NA", "San Rafael", 94912)

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("propaneKing", "hHill@propane.com", "Hi I'm Hank Hill. I love drinking beer in the yard with my friends and talking about propane and propane accesories. I work at the local propane store.", "propane and propane accessories, mowing my lawn, bbq", 45, 1800, 90, 76, 85, true, false, "NA", "Houston", 77021)

INSERT INTO homies (user, email, phone, bio, hobbies, age, gender, budget, finance_score, clean_score, personality_score, job_title, employed, drugs, drug_type, city, zip_code) VALUES ("nuclearhomer", "hsimpson@burnsnuclear.org", 2178483023, "Hi my name is Homer Simpson. I work at the local nuclear plant controlling the fission reactions. I know it sounds hard but its really easy. I barely have to be there. This leaves lots of time for me to get into fun adventures", "drinking at moes, donuts mmmmmmm, itchy & scratchy", 46, 85, 70, 90, "Springfield", 62708)